name: CI
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to PyPI'
        required: false
        type: boolean
        default: false
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
  release:
    types:
      - published

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    name: Test Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e . pytest
      - name: Run tests
        run: pytest

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read   # Required to checkout the code
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use a stable version for building
      - name: Install build dependencies
        run: pip install build twine
      - name: Build wheels
        run: python -m build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
      - name: Publish to PyPI
        # Publish on releases or when manually triggered with publish=true
        if: (github.event_name == 'release' && github.event.action == 'published') || (github.event_name == 'workflow_dispatch' && inputs.publish)
        uses: pypa/gh-action-pypi-publish@release/v1
